/*global systemDictionary:true */
"use strict";

systemDictionary = {
  "nissan adapter settings": {
    en: "Adapter settings for nissan",
    de: "Adaptereinstellungen für nissan",
    ru: "Настройки адаптера для nissan",
    pt: "Configurações do adaptador para nissan",
    nl: "Adapterinstellingen voor nissan",
    fr: "Paramètres d'adaptateur pour nissan",
    it: "Impostazioni dell'adattatore per nissan",
    es: "Ajustes del adaptador para nissan",
    pl: "Ustawienia adaptera dla nissan",
    "zh-cn": "nissan的适配器设置",
  },
  "Nissan App Email": {
    en: "Nissan App Email",
    de: "Nissan App Email",
    ru: "Имя пользователя приложения",
    pt: "Nome de usuário do aplicativo",
    nl: "App-gebruikersnaam",
    fr: "Nom d'utilisateur de l'application",
    it: "Nome utente dell'app",
    es: "Nombre de usuario de la aplicación",
    pl: "Nazwa użytkownika aplikacji",
    "zh-cn": "应用用户名",
  },
  "Nissan App Password": {
    en: "Nissan App Password",
    de: "Nissan App-Passwort",
    ru: "Пароль приложения",
    pt: "Senha de app",
    nl: "App-wachtwoord",
    fr: "Mot de passe de l'application",
    it: "Password dell'app",
    es: "Contraseña de la aplicación",
    pl: "Hasło do aplikacji",
    "zh-cn": "应用密码",
  },
  "Update interval in minutes": {
    en: "Update interval in minutes",
    de: "Aktualisierungsintervall in Minuten",
    ru: "Интервал обновления в минутах",
    pt: "Intervalo de atualização em minutos",
    nl: "Update-interval in minuten",
    fr: "Intervalle de mise à jour en minutes",
    it: "Intervallo di aggiornamento in minuti",
    es: "Intervalo de actualización en minutos",
    pl: "Interwał aktualizacji w minutach",
    "zh-cn": "以分钟为单位的更新间隔",
  },
  "Force Update to receive new data. This will drain 12V Battery. Please check 12V Battery": {
    en: "Force Update to receive new data. This will drain 12V Battery. Please check 12V Battery",
    de: "Update erzwingen, um neue Daten zu erhalten. Dies wird 12V Batterie leer machen. Bitte überprüfen die 12V Batterie regelmässig",
    ru: "Обновление силы для получения новых данных. Это будет слить 12V батареи. Пожалуйста, проверьте 12V батареи",
    pt: "Force Update para receber novos dados. Isto irá drenar a bateria 12V. Por favor, verifique 12V bateria",
    nl: "Force Update om nieuwe gegevens te ontvangen. Dit zal 12V Battery leegzuigen. Controleer alsjeblieft 12V Battery",
    fr: "Mise à jour de la Force pour recevoir de nouvelles données. Cela va drainer 12V Batterie. S'il vous plaît vérifier 12V Batterie",
    it: "Force Update per ricevere nuovi dati. Questo prosciugherà la batteria 12V. Si prega di controllare la batteria 12V",
    es: "Actualización de fuerzas para recibir nuevos datos. Esto drenará la batería 12V. Por favor, compruebe la batería 12V",
    pl: "W celu uzyskania nowych danych. Zajmuje to 12V Battery. Zaprezentować 12V Battery",
    uk: "Оновлення Force для отримання нових даних. Це зливить 12V акумулятор. Будь ласка, перевірте 12V акумулятор",
    "zh-cn": "接收新资料的部队最新情况。 这将减少12V Battery。 请检查12V Battery",
  },
};
