/*global systemDictionary:true */
"use strict";

systemDictionary = {
    "nissan adapter settings": {
        en: "Adapter settings for nissan",
        de: "Adaptereinstellungen für nissan",
        ru: "Настройки адаптера для nissan",
        pt: "Configurações do adaptador para nissan",
        nl: "Adapterinstellingen voor nissan",
        fr: "Paramètres d'adaptateur pour nissan",
        it: "Impostazioni dell'adattatore per nissan",
        es: "Ajustes del adaptador para nissan",
        pl: "Ustawienia adaptera dla nissan",
        "zh-cn": "nissan的适配器设置",
    },
    user: {
        en: "App Username",
        de: "App-Benutzername",
        ru: "Имя пользователя приложения",
        pt: "Nome de usuário do aplicativo",
        nl: "App-gebruikersnaam",
        fr: "Nom d'utilisateur de l'application",
        it: "Nome utente dell'app",
        es: "Nombre de usuario de la aplicación",
        pl: "Nazwa użytkownika aplikacji",
        "zh-cn": "应用用户名",
    },
    password: {
        en: "App Password",
        de: "App-Passwort",
        ru: "Пароль приложения",
        pt: "Senha de app",
        nl: "App-wachtwoord",
        fr: "Mot de passe de l'application",
        it: "Password dell'app",
        es: "Contraseña de la aplicación",
        pl: "Hasło do aplikacji",
        "zh-cn": "应用密码",
    },
    interval: {
        en: "Update interval in minutes",
        de: "Aktualisierungsintervall in Minuten",
        ru: "Интервал обновления в минутах",
        pt: "Intervalo de atualização em minutos",
        nl: "Update-interval in minuten",
        fr: "Intervalle de mise à jour en minutes",
        it: "Intervallo di aggiornamento in minuti",
        es: "Intervalo de actualización en minutos",
        pl: "Interwał aktualizacji w minutach",
        "zh-cn": "以分钟为单位的更新间隔",
    },
};
